In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("mix_fee_assets.csv")
df

                              Unnamed: 0  bills  bonds  equity    fee
0    Checking or regular savings account      1    0.0     0.0  0.010
1  High interest/premium savings account      1    0.0     0.0  0.000
2                           Mutual funds      0    0.4     0.6  0.015
3                                 Stocks      0    0.0     1.0  0.025
4                                  Bonds      0    1.0     0.0  0.025
5                                   GICs      1    0.0     0.0  0.005
6    Cash value of permanent life policy      0    1.0     0.0  0.020
7            Individual segregated funds      0    0.4     0.6  0.020
8                                   ETFs      0    0.0     1.0  0.005